# Plister OS X preference file
# See https://github.com/benbalter/plister

# System-wide settings stored in /Library/Preferences
system:
  com.apple.SoftwareUpdate:
    AutomaticCheckEnabled: true
    AutomaticallyInstallMacOSUpdates: true
    AutomaticDownload: true
    CriticalUpdateInstall: true
    ConfigDataInstall: true

  com.apple.commerce:
    AutoUpdate: true

  com.apple.FindMyMac:
    FMMEnabled: true

# User-specific settings stored in ~/Library/preferences
user:
  com.apple.screensaver:
    askForPassword: 1
    askForPasswordDelay: 0

  com.apple.screencapture:
    location: ~/Desktop
    type: png
    disable-shadow: true

  com.apple.AppleMultitouchTrackpad:
    TrackpadRightClick: true
    TrackpadPinch: 1
    USBMouseStopsTrackpad: 0
    TrackpadFourFingerVertSwipeGesture: 2
    ActuateDetents: 1
    FirstClickThreshold: 1
    SecondClickThreshold: 1
    TrackpadTwoFingerDoubleTapGesture: 1
    TrackpadHorizScroll: 1
    TrackpadMomentumScroll: true
    TrackpadFourFingerPinchGesture: 2
    UserPreferences: true
    Clicking: true
    TrackpadRotate: 1
    TrackpadThreeFingerTapGesture: 2
    TrackpadThreeFingerHorizSwipeGesture: 0
    DragLock: 0
    TrackpadFiveFingerPinchGesture: 2
    ForceSuppressed: false
    TrackpadThreeFingerVertSwipeGesture: 0
    TrackpadTwoFingerFromRightEdgeSwipeGesture: 3
    TrackpadScroll: true
    TrackpadHandResting: true
    Dragging: false
    TrackpadCornerSecondaryClick: 0
    TrackpadFourFingerHorizSwipeGesture: 2
    TrackpadThreeFingerDrag: true

  com.apple.dock:
    show-recents: false
    autohide: true
    orientation: left

  com.apple.menuextra.battery:
    ShowPercent: 'YES'

  com.apple.assistant.support:
    Siri Data Sharing Opt-In Status: 1
    Assistant Enabled: false

  com.apple.Siri:
    StatusMenuVisible: false

  com.apple.finder:
    NewWindowTargetPath: file:///Users/kevinbisner/
    FXICloudDriveDesktop: false
    FXICloudDriveDocuments: false
    FXICloudDriveEnabled: true
    ShowMountedServersOnDesktop: true
    ShowHardDrivesOnDesktop: false
    ShowRemovableMediaOnDesktop: true
    ShowExternalHardDrivesOnDesktop: true
    SidebarDevicesSectionDisclosedState: true
    SidebarShowingiCloudDesktop: false
    FK_StandardViewSettings:
      SettingsType: FK_StandardViewSettings
      ExtendedListViewSettingsV2:
        sortColumn: kind
      ListViewSettings:
        sortColumn: kind
      IconViewSettings:
        arrangeBy: kind
    FavoriteTagNames:
      - ''
      - Critical
      - Important
      - Valuable
      - Giveaway
      - Learning
      - Heroku
      - Temp
    DesktopViewSettings:
      IconViewSettings:
        arrangeBy: kind
    NewWindowTarget: PfHm
    StandardViewSettings:
      IconViewSettings:
        arrangeBy: kind
      ListViewSettings:
        sortColumn: kind
      ExtendedListViewSettingsV2:
        sortColumn: kind
      GalleryViewSettings:
        arrangeBy: kind
    FXPreferredGroupBy: Kind

  # Global domain-less preferences (NSGlobalDomain)
  .GlobalPreferences:
    NSAutomaticDashSubstitutionEnabled: false
    NSAutomaticQuoteSubstitutionEnabled: false
    WebAutomaticTextReplacementEnabled: true
    WebKitDeveloperExtras: true
